name: flutter_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  image_cropper: ^3.0.3
  image_picker: ^0.8.4+4
  photo_manager: ^2.8.1
  provider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# Override the photo_manager dependency to use a pre-release version
dependency_overrides:
  photo_manager: ^3.0.0-dev.2
